name: thai_hymn
version: 0.0.1+1

environment:
  sdk: ">=2.19.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # play videos
  video_player: ^2.2.11
  chewie: ^1.6.0+1
  wakelock_plus: ^1.0.0+3

  equatable: ^2.0.3
  get: ^4.6.1

  shared_preferences: ^2.0.11

  flutter_native_splash: ^2.0.5
  rename: ^2.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: '##1CACE3'
  image: assets/images/splash.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videofile/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: angsana
      fonts:
        - asset: assets/fonts/angsana.ttc